name: main
on: [push, pull_request]

env:
  CLICOLOR_FORCE: 1

jobs:
  main:
    strategy:
      fail-fast: false
      matrix:
        buildtype: [Release, RelWithDebInfo, Debug]
    runs-on: ubuntu-latest
    container: debian:13
    steps:
    - name: Install dependencies
      run: |
        apt-get update
        apt-get -y upgrade  \
          clang-format clang-tidy cmake g++ git ninja-build python3  \
          libboost1.88-dev libboost-json1.88-dev qml6-module-qtquick qt6-declarative-dev
    - name: Checkout
      uses: actions/checkout@v4
    - name: Configure
      run: cmake -G Ninja -B build -DCMAKE_COMPILE_WARNING_AS_ERROR=ON -DCMAKE_BUILD_TYPE=${{matrix.buildtype}}
    - name: Build
      run: ninja -C build -k 0
    - name: Lint
      run: ninja -C build -k 0 lint
